version: '2'
services:
  vulnerable_container:
    image: 'nsunina/cve-2019-14287:latest'
    stdin_open: true
    tty: true
    networks:
      vulnerable_network:
        ipv4_address: 193.20.1.2
  ssh_client:
    image: 'nsunina/alpine_ssh:latest'
    stdin_open: true
    tty: true
    networks:
      vulnerable_network:
        ipv4_address: 193.20.1.3
networks:
  vulnerable_network:
    ipam:
      config:
        - subnet: 193.20.1.1/24
