version: '2'
services:
  vulnerable_container:
    image: 'nsunina/path_privesc:latest'
    stdin_open: true
    tty: true
    networks:
      vulnerable_network:
        ipv4_address: 193.20.1.2
networks:
  vulnerable_network:
    ipam:
      config:
        - subnet: 193.20.1.1/24
